import { create } from 'zustand'
import { LOAD_TYPING_TESTS, TYPING_HISTORY } from '../../../api'

export type TypingLanguage = 'english' | 'hindi'
export type TypingAction = 'start' | 'resume' | 'solution'
export type TypingTest = {
    testId: string; title: string; language: TypingLanguage; level: number; levelName: string; duration: number; words?: number; access?: boolean; available?: boolean
    actions?: { primary?: TypingAction | 'test-again'; resumeHistoryId?: string; solutionHistoryId?: string }
    history?: Array<{ historyId?: string; status?: string; score?: number; accuracy?: number }>
}
export type TypingHistory = { resultId: string; testId: string; title: string; attemptedAt: number; duration: number; level: number; levelName: string; netWpm: number; grossWpm: number; accuracy: number; rank?: number }
type Store = {
    language: TypingLanguage; selectedLevel: string; duration: number; backspaceEnabled: boolean; highlightEnabled: boolean; liveSpellingEnabled: boolean
    levelAccess: Record<string, boolean>; levelProgress: Record<string, { total: number; passed: number; percent: number; minimumSpeed: number; minimumAccuracy: number; complete: boolean }>
    tests: TypingTest[]; history: TypingHistory[]; loadingTests: boolean; loadingHistory: boolean; testsHasMore: boolean; historyHasMore: boolean; testPage: number; historyPage: number
    testsCache: Record<string, { pages: Record<number, TypingTest[]>; hasMore: Record<number, boolean>; levelAccess: Record<string, boolean>; levelProgress: Record<string, { total: number; passed: number; percent: number; minimumSpeed: number; minimumAccuracy: number; complete: boolean }> }>
    pendingTest: { testId: string; action: TypingAction; historyId: string } | null
    setLanguage: (language: TypingLanguage) => void; setSelectedLevel: (level: string) => void; setDuration: (duration: number) => void; setSetting: (setting: 'backspaceEnabled' | 'highlightEnabled' | 'liveSpellingEnabled', value: boolean) => void
    setPendingTest: (testId: string, action: TypingAction, historyId?: string) => void; clearPendingTest: () => void
    clearTestsCache: () => void
    applyTypingTestUpdate: (update: { testId?: string; historyItem?: NonNullable<TypingTest['history']>[number]; actions?: TypingTest['actions'] }) => void
    loadTests: (level?: string, page?: number, reset?: boolean, language?: TypingLanguage) => Promise<void>; loadHistory: (page?: number, reset?: boolean, testId?: string) => Promise<void>
}
const normalizeTest = (test: any): TypingTest => ({ testId: String(test.testId || test._id || test.id || ''), title: test.title || test.n || test.name || 'Typing Test', language: ['hn', 'hindi'].includes(String(test.lan || test.language || 'en').toLowerCase()) ? 'hindi' : 'english', level: Number(test.level || 1), levelName: test.levelName || ['Easy', 'Medium', 'Hard', 'Expert', 'Master'][Math.max(0, Number(test.level || 1) - 1)] || 'Easy', duration: Number(test.duration || 1), words: Number(test.words || test.w || test.wordCount || 0), access: test.access, available: test.available, actions: test.actions, history: test.history })
export const useTypingStore = create<Store>((set, get) => ({
    language: 'english', selectedLevel: 'Easy', duration: 1, backspaceEnabled: true, highlightEnabled: true, liveSpellingEnabled: true, levelAccess: { Easy: true }, levelProgress: {},
    tests: [], history: [], loadingTests: false, loadingHistory: false, testsHasMore: true, historyHasMore: true, testPage: 1, historyPage: 1, pendingTest: null, testsCache: {},
    setLanguage: (language) => set({ language }), setSelectedLevel: (selectedLevel) => set({ selectedLevel }), setDuration: (duration) => set({ duration }), setSetting: (setting, value) => set({ [setting]: value }), setPendingTest: (testId, action, historyId = '') => set({ pendingTest: { testId, action, historyId } }), clearPendingTest: () => set({ pendingTest: null }), clearTestsCache: () => set({ testsCache: {} }), applyTypingTestUpdate: (update) => { if (!update.testId || !update.historyItem || !update.actions) return; const apply = (test: TypingTest) => test.testId === update.testId ? { ...test, history: [update.historyItem!], actions: update.actions } : test; set((state) => { const testsCache = Object.fromEntries(Object.entries(state.testsCache).map(([key, entry]) => [key, { ...entry, pages: Object.fromEntries(Object.entries(entry.pages).map(([page, tests]) => [page, tests.map(apply)])) }])); return { tests: state.tests.map(apply), testsCache } }) },
    loadTests: async (level = get().selectedLevel, page = 1, _reset = true, language = get().language) => { const key = `${language}:${level}`; const cached = get().testsCache[key]; const applyCached = (entry: NonNullable<typeof cached>) => { const pages = Object.keys(entry.pages).map(Number).filter((number) => number <= page).sort((a, b) => a - b); const tests = pages.flatMap((number) => entry.pages[number]); set({ tests, testPage: pages.at(-1) || 1, selectedLevel: level, levelAccess: entry.levelAccess, levelProgress: entry.levelProgress, testsHasMore: entry.hasMore[pages.at(-1) || 1] ?? true }) }; if (cached?.pages[page]) { applyCached(cached); return } if (get().loadingTests) return; set({ loadingTests: true }); try { const response = await fetch(LOAD_TYPING_TESTS, { method: 'POST', credentials: 'include', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ level, lan: language === 'hindi' ? 'hn' : 'en', page, limit: 8 }) }); const data = await response.json(); if (!data?.success) return; const tests = (data.tests || data.typingTests || data.data || []).map(normalizeTest).filter((item: TypingTest) => item.testId); set((state) => { const previous = state.testsCache[key] || { pages: {}, hasMore: {}, levelAccess: state.levelAccess, levelProgress: state.levelProgress }; const entry = { ...previous, pages: { ...previous.pages, [page]: tests }, hasMore: { ...previous.hasMore, [page]: Boolean(data.pagination?.hasMore ?? data.hasMore ?? tests.length >= 8) }, levelAccess: data.levelAccess || previous.levelAccess, levelProgress: data.levelProgress || previous.levelProgress }; const pages = Object.keys(entry.pages).map(Number).filter((number) => number <= page).sort((a, b) => a - b); return { testsCache: { ...state.testsCache, [key]: entry }, tests: pages.flatMap((number) => entry.pages[number]), testPage: pages.at(-1) || 1, selectedLevel: level, levelAccess: entry.levelAccess, levelProgress: entry.levelProgress, testsHasMore: entry.hasMore[pages.at(-1) || 1] ?? true } }) } finally { set({ loadingTests: false }) } },
    loadHistory: async (page = 1, reset = true, testId = '') => { if (get().loadingHistory) return; set({ loadingHistory: true }); try { const response = await fetch(TYPING_HISTORY, { method: 'POST', credentials: 'include', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ testId, lan: get().language === 'hindi' ? 'hn' : 'en', page, limit: 8 }) }); const data = await response.json(); if (!response.ok || !data?.success) return; const history = data.history || data.results || []; set((state) => ({ history: reset ? history : [...state.history, ...history], historyPage: page, historyHasMore: Boolean(data.pagination?.hasMore ?? data.hasMore ?? history.length >= 8) })) } finally { set({ loadingHistory: false }) } }
}))
